[workspace]
pr_draft = false
changelog_config = "cliff.toml"
pr_labels = ["release"]
git_release_name = "{{ crate_name }}-v{{ version }}"
commit_message = "chore(release): {{ crate_name }} v{{ version }} [skip ci]"
publish = true
git_tag_enable = true
changelog_update = true

[[package]]
name = "nami"
git_release_name = "v{{ version }}"
git_tag_name = "v{{ version }}"

[[package.files_to_update]]
path = "README.md"
search = 'nami = "[0-9]+\\.[0-9]+(\\.[0-9]+)?"'
replace = 'nami = "{{ version }}"'

[[package]]
name = "nami-core"
git_tag_name = "core-v{{ version }}"

[[package]]
name = "nami-derive"
git_tag_name = "derive-v{{ version }}"